name: 🟣 k6 Advanced Benchmark

on:
  workflow_dispatch:

jobs:
  k6-advanced-test:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@v4

      - name: 💾 Install k6
        run: |
          sudo apt-get update
          sudo apt-get install -y gnupg2 ca-certificates
          curl -s https://dl.k6.io/key.gpg | sudo apt-key add -
          echo "deb https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install -y k6

      - name: 📦 Install system monitoring tools
        run: |
          sudo apt-get install -y sysstat gnuplot

      - name: 🧪 Start system metric monitors
        run: |
          pidstat -durh 1 > pidstat.log &
          echo $! > pidstat_pid.txt

          (while true; do top -b -n1 | head -30 >> top.log; sleep 3; done) &
          echo $! > top_pid.txt

          (while true; do ps -o pid,cmd -C k6 >> threads_raw.log 2>/dev/null; sleep 1; done) &
          echo $! > thread_pid.txt

      - name: Run k6 Advanced Test
        run: |
          echo "Running k6 test..."
          mkdir -p results

          /usr/bin/time -v \
            k6 run k6/scripts/test.js \
            --out json=results/k6_results.json \
            2> time_metrics.txt

      - name: 🛑 Stop monitors
        if: always()
        run: |
          kill $(cat pidstat_pid.txt) || true
          kill $(cat top_pid.txt) || true
          kill $(cat thread_pid.txt) || true

      - name: 📊 Extract thread count timeline
        run: |
          awk '{print $1}' threads_raw.log > threads.log || true

      - name: 📂 Upload Advanced Benchmark Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: k6-advanced-results
          path: |
            pidstat.log
            top.log
            threads.log
            threads_raw.log
            time_metrics.txt
            results/
            k6/scripts/test.js
